### local config
GET http://localhost:8088/config/local
Accept: application/json

### dev config
GET http://localhost:8088/option/option
Accept: application/json

### monitor
POST http://localhost:8088/monitor
Content-Type: application/json
X-Event-Key: repo:push
X-Hook-UUID: webhook-uuid
Accept: application/json

{
"push": {"changes": []}
}


