server:
  port: 8088
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ysjune/spring-cloud-config-repository-test
          searchPaths:
            - '{application}'
            - '{application}/*'
    bus:
      enabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: glen
    password: glen
